model:
  model_params: {'bins': 1024, 'unstable_bins': 0, 'reduction_bins': 0, 'band': {1: {'sr': 44100, 'hl': 512, 'n_fft': 2048, 'crop_start': 0, 'crop_stop': 1024, 'hpf_start': -1, 'res_type': 'sinc_best'}}, 'sr': 44100, 'pre_filter_start': 1023, 'pre_filter_stop': 1024, 'mid_side': False, 'mid_side_b': False, 'mid_side_b2': False, 'stereo_w': False, 'stereo_n': False, 'reverse': False}
  nout: null
  nout_lstm: null

training:
  target_instrument: null
  instruments: ['Instrumental', 'Vocals'] # [primary_stem, secondary_stem]
  use_amp: false

inference:
  batch_size: 1
  aggression: 5
  high_end_process: false
  post_process_threshold: 0.2
  window_size: 512

audio:
  sample_rate: 44100